### ISSUE TITLE
Weekly Log for Noam Yefet

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartCity-Market#286]
# The Weekly Log
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with. 

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here *_past_* work that is finished, as well as *_current_* tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized. 

**Have a great semester!**

**Comment by noamyft** [comment]
Weekly log for week 1 (19.3-25.3):

- [x] set-up the environment in my new computer

- [x] rearrange lables

**Comment by TomPalny** [comment]
Hi Noam, any **bug** that you are working on, for example the one from last week, should have an issue number attached to it, or it doesn't count as work

**Comment by noamyft** [comment]
Weekly log for week 2 (26.3-1.4):

- [x] design screen for cart&costumer (with Lior)

- [x] Planning a schedule and milestones for sprint 3 and sprint 4

- [x] Write wiki of milestone for sprint 3

- [x] Write wiki of milestone for sprint 4

- [x] Explore warnings and spartanizer options and write code conventions for them (in the Wiki of code conventions).

- [x] Write Wiki explains the labels meanings

- [x] Fix bug: cart can checkout even if grocery list is empty (issue  #264)

- [x] Bug fix: The server remove the products in cart on cancel  (issue #282)
note: this bug revealed the following bug and a serious bug that is found in the HSQLDB library. This is why it took time to find and fix those three bugs.

- [x] Bug fix: Products returned to shelves after check out (issue: #344)

**Comment by noamyft** [comment]
Weekly log for week 3 (2.4-8.4):

- [x] Modify the sql database to fit sprint 3 #360

- [x] Replace "Cart" username to "Guest" #362

**Comment by TomPalny** [comment]
Hi Noam,
Please write your work log for weeks 5 & 6. (week 4 was Passover). Don't forget to reference the issues you are currently working on.

**Comment by noamyft** [comment]
Weekly log for week 4 (9.4-15.4):
Passover vacation

**Comment by noamyft** [comment]
Weekly log for week 5 (16.4-22.4):

- [x] Add login command for customer in SQL classes #365

- [x] Add support to add / remove ingredient from server side #333

- [x] Add support to add / remove / edit / get_list manufactors from server side #334

- [x] Add support to add / remove customers from server side #335

- [x] Add support to add / remove workers from server side #336

**Comment by noamyft** [comment]
Weekly log for week 6 (23.4-29.4):

continue work on:

- [x] Add login command for customer in SQL classes #365

- [x] Add support to add / remove ingredient from server side #333

- [x] Add support to add / remove / edit / get_list manufactors from server side #334

- [x] Add support to add / remove customers from server side #335

- [x] Add support to add / remove workers from server side #336

and also:


- [x] Fix presentation for Mid-Sprint3 presentation #388 

- [x] Add support of edit profile for customer in SQL database #384

- [x] Add support to security Question and answer for customer in SQL database #385 

- [x] Add IS_FREE_CUSTOMER_NAME method to sql #373 

- [x] Add IS_FREE_WORKER_NAME method to sql #405

- [x] add method GET_ALL_WORKERS in sql #404

- [x] Add error on server side: ingredient still in used  #400

- [x] Add error on server side: manufaturer still in used #399

- [x] integration of all above commands: #394 #395 #396 #398 #401 #402 #405

**Comment by noamyft** [comment]
Weekly log for week 7 (30.4-6.5):

- [x] Research on AI & machine learning #415

- [x] Start design of new module (seggestion and bargaining of sales)

**Comment by noamyft** [comment]
Weekly log for week 8 (7.5-13.5):
My Week Off

- [x] Continue design of new module (seggestion and bargaining of sales)

**Comment by noamyft** [comment]
Weekly log for week 9 (14.5-20.5):
My Week Off (my sister wedding)

- [x] Continue design of new module (seggestion and bargaining of sales)

**Comment by noamyft** [comment]
Weekly log for week 10 (21.5-27.5):

- [x] Create DB support for forget password  #409

- [x] Bug fix: Customer.registerNewCustomer(customerProfile) - get error from server  #412

- [x] Bug Fix login commands on server side  #418

- [x] Correct incompatibility in command: GetIngreidientList #420

- [x]  Bug fix: error when renaming manufacturer #424 

- [x] Add full support to Forgot Password flow  #425

- [x] Integrate "forget password" flow in server  #436

**Comment by noamyft** [comment]
Weekly log for week 11 (28.5-3.6):

- [x] Fix Bug: Critical Error been threw by Database while renaming manufacturer  #432

- [x] Add test and Bug fixes in customer registration #441

- [x] Add test and Bug fixes in customer get/set profile #441

- [x] Add more tests and improve code coverage of customer operations in SQL database  #442

- [x] Fix Bug in Database when renaming ingredient #443 

- [x] Refactor code and fix update queries in SQL  #444

- [x] Add Forgot Password flow to workers too  #445

- [x] Integrate Forgot Password flow to CommandExecuter  #446

**Comment by noamyft** [comment]
Weekly log for week 12 (4-10.6):

- [x]  Correct incompatibility in command: getAllWorkers #455 

- [x] Fix Bug in SQL when adding multiple ingredients & manufacturers  #457

- [x] Trying to export the project to jar and fix resources problem #460

- [x] Add data to database for the "Client Game"  #462


Sales module:

- [x] Learning to use Java Stream for doing advance filtering  #476

- [x] Add class structure to Sales module  #481 

- [x] Start to extract properties to deduction algorithm  #482

**Comment by noamyft** [comment]
Weekly log for week 13 (11-17.6):

- [x] Start design and update SQL tables to support sales (regular sales, group sales and suggested sales) #503

Sales module:

- [x] Redesign and edit class structure to Sales module  #481

- [x] Continue Extract properties to deduction algorithm  #482

- [x] Add Most popular product property  #483

- [x] Add Testing modules and mocks to Sales module  #484

- [x] Continue to Learning to use Java Stream for doing advance filtering #476

**Comment by noamyft** [comment]
Weekly log for week 14 (18-24.6):

- [x]  Finish design and update SQL tables to support sales (regular sales, group sales and suggested sales) #508

- [x] Add operations to support sales in sql for manager  #504 #503

- [x] Add operations to support sales in sql for customer  #505 #503  

- [x] Add operation to sql: get all expired packages  #506

- [x] Add operation to sql: get all packages  #507

- [x] Integrate sql operations into server to support sales  #509

- [x] Integrate sql operation: get all expired packages into server  #510

- [x] Add SQL operation: getAllProductsInCatalog  #514

**Comment by noamyft** [comment]
Weekly log for week 15 (25.6-1.7):

- [x] Continue to work on last week issues

- [x] Fix Bug: get all expired packages returns the not expired packages #528

- [x] Add property: LastPopularityProductProperty  #517

- [x] Add property: AbouteToExpireLate Property  #519

- [x] Add property: High Ratio Amount/(days to expire) Property  #520

- [x] Add deduction: AboutToExpireSoon => MustGetRidOfPackage  #523
 -[x] Add deduction: AboutToExpireLate => MayGetRidOfPackage  #527 
- [x] Redesign Sales module  #529 

- [x] Add Deduction Rule: if must get rid of then sale by multiply factor  #530

- [x] Finish build deducer & decider  #531

- [x] Finish build suggestor - make suggestion method  #532

- [x] Add Properties: buyers amount & income per month  #533

- [x] Sales: Add More Basic Properties  #534

- [x] Sales: Add more deduction rules  #535 

- [x] Fix offers of the Sales module #539

- [x] Add producing explainations in the sales module #540

- [x] Finish integration of Sales module to Server #543

**Comment by noamyft** [comment]
Weekly log for week 15 (2-4.7):

- [x] Participate in The "Reality Test"

- [x] Fix Bugs
