### ISSUE TITLE
Weekly Log for Shimon Azulay

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/SmartCity-Market#287]
# The Weekly Log
New for semester 2, a fresh new page with a different name.
This is meant to help in monitoring everyone's assignments in the projects and what they are currently involved with. 

Please use this as a weekly log from week 2 till the end of semester, both for you and me to see.
Log here *_past_* work that is finished, as well as *_current_* tasks you are doing.

Whenever possible, please include an issue number that you are working on, or that you have finished working on.
Best to use the bulleted list as a way to put things organized. 

**Have a great semester!**

**Comment by shimonAzulay** [comment]
Week 2: 
- [x] Finding and fixing bugs in the project  #276 #313 #314 #318
- [x] Integrate ControlsFx to project #256
- [x] Write Wiki on persistence #123
- [x] Create infrastructure for persistence in the project #123

**Comment by shimonAzulay** [comment]
Week 3:

- [x] Adding parameter for lunch the Employee for showing the main screen video or not #347 
- [x] Improve TextField #353
- [x] Improve RadioButtons and CheckBoxes   #350
- [x] Improve Datepicker  #351
- [x] Bug fixs and general improvements

**Comment by shimonAzulay** [comment]
Week 4:
- [x] add date picker slide animation #376
- [x] improve GUI text field in Manage catalog product tab #377

Continue working on those issues on week 
-  Improve spinner #357 
- Use TextFields with history #337
- Add Manufacturers and Ingredients  option in GUI and Logic #310

**Comment by shimonAzulay** [comment]
Week 5;
- [x] Use popup for manual date picker in manage packages tab #391

**Continue from Week 4:**
- [x] Improve spinner #357 
- [x] Add Manufacturers and Ingredients  option in GUI and Logic #310

**Comment by shimonAzulay** [comment]
week 6:
- [x] Use TextFields with history #337
- [x] Create ForgetPassword GUI #355 
- [x] Connect the SQL support for ingredients and manufacturer to the GUI with the LOGIC #408
- [x] Remove stack trace prints and from all over the project #390

**Comment by TomPalny** [comment]
Good work! keep it up.

**Comment by shimonAzulay** [comment]
Week 7: 
Week off

**Comment by shimonAzulay** [comment]
Week 8:

- [x] Add to manager GUI employees manager tab #308
- [x] Skype meeting issues #423
- [x] Bugs in Ingredients and Manufacturers flow #424
- [x] Refactor in Error dialog service #426 
* Refactor in LOG #427

**Comment by shimonAzulay** [comment]
Week 9:
- [x] Create service to convert stacktrace to string #431
- [x] Add full support to Forgot Password flow #425 
- [x] Refactor in project Exceptions #434

**Continue from Week 8:**

- Refactor in LOG #427 
- [x] Bugs in Ingredients and Manufacturers flow #424

**Comment by shimonAzulay** [comment]
Week 10:

- [x] Refactor in ForgotPassword from Employee and Costumer #438

-  improve css for all project #374

- [x] Add full support to Forgot Password flow #425

**Continue from Week 9:**
- Refactor in LOG #427

**Comment by shimonAzulay** [comment]
Week 11:
- [x] Bugs in customer registration flow #441
- [x] The GUI not fit to screen resolution #278 
- [x] Bug in forgot password in Customer #447
- [x] Change the login failure message #449
- [x] Screen resolution bug when error dialog appeared #450
- [x] Bug new worker registration #448
- [x] Add icons to project #452
- [x] Enhancement in Dialog util - Add yes, no dialog #453

Continue from week 10:
- [x] improve css for all project #374
* Refactor in LOG #427

**Comment by shimonAzulay** [comment]
Week 12:

- [x] Bugs in Ingredients and Manufacturers flow #424
- [x] Logout bug #456
- [x] Improve customer Main screen #366 
- [x] End of Sprint 3 - Course meeting - 05/06 #472
*  Improve GUI #475

**Comment by shimonAzulay** [comment]
Week 13:
- [x] Bug in catalog product details - can add two same Ingr' and Manu' #474
- [x] Manage Catalog products tab - fix switch case manufacturar #473
- [x] Use eventbus to inform screens about add/remove manu' and ingr' #485
- [x] Show ingredients in more info- Employee #468
- [x] Bug in manager: not sending the ingredients to the server #461

**Comment by shimonAzulay** [comment]
Week 14:
- [x] Refactor in LOG #427
- [x] Add Configuration screen and logic #488 
- [x] Add Sales part in customer dashboard #495
- [x] Create Sales Tab in Manager #494

**Comment by shimonAzulay** [comment]
Week 15:
- [x] Add location support for Manager tab #501
- [x] Improve GUI #475
- [x] Add full support to search & display products locations in Customer #526
- [x] Logger in Worker tabs #502
- [x] Expired Products - GUI #499
- [x] Fix Bugs and GUI in Sale Tab - Manager #518
- [x] Add support to special sale #524
- [x] User is not logged out when pressing the "door button" in Customer screen #471
- [x] Bugs and Enhancements #538
- [x] Application arguments #544
