### ISSUE TITLE
Group Meeting - April 3rd

### ISSUE THREAD

**Issue by LiorBenAmi** [TechnionYP5777/SmartCity-Market#345]
## Tasks Devision for the next week:

* General tasks division. please take each bullet to a specific issue. 
It's not a contract - only scretch and can be edit later
- [x] finish install me wiki - Idan
- [x] add screen shot of success in testing - Aviad
- [x] forget password (common) - shimon

Employee
- [x] worker - set parameter to enable/disable video - shimon
- [x] Employee- Improve Employee GUI - shimon
- [x] Add to Manager the GUI option of adding Ingredients and manufacturers to system - shimon
- [x] Unit Tests for BL of adding Ingredients and manufacturers to system. - shimon

Costumer:
- [x] finish integration - Aviad
- [x] restore grocery list - check the flow  - lior & noam
- [x] unit tests - lior/Aviad/Idan
**gui:**
- [x] login/logout - lior
- [x] registration pages - lior

Server:

misc.: Idan is in week off due duty service. @IdanAtias please don't forget us and implement customer logic ;)

@shimonAzulay  @AviadCo  @noamyft
